### ISSUE TITLE
Cordova arch error

### ISSUE THREAD

**Issue by boomfly** [zodern/melte#3]
If build cordova targets get error:

`Uncaught TypeError: Class constructor SvelteComponentDev cannot be invoked without 'new'`

https://github.com/meteor/meteor/blob/c7534dbcddd3c677efb6297e67132b05bd63dc87/packages/babel-compiler/babel-compiler.js#L90

This line makes modernBrowsers only for web.browser arch, but svelte need it if we compile web.cordova

**Comment by r00t3g** [comment]
There is a work around how to make babel proprly transpile svelte's internals: https://forums.meteor.com/t/transpile-certain-node-modules-with-babel-at-meteor-build/48546

You just need to link the svelte package from node-modules inside any of meteor-watchable directories, e.g. /imports

**Comment by zodern** [comment]
I don't have a cordova project to test with, but if anyone wants to, feel free to submit a PR documenting how to fix this.

**Comment by r00t3g** [comment]
I am not sure that it is really a melte problem as it seems to be related to the way meteor-babel handles node_modules imports... However, it is possible to reproduce it without cordova, using some legacy browser (ie 11 would do). I'll try to have a look at it - perhaps will find something

**Comment by zodern** [comment]
Thanks @r00t3g. I tried the legacy client, and melte itself also caused syntax errors. I published zodern:melte@1.4.1 to fix that, and also document how to have Meteor recompile `svelte`.
