### ISSUE TITLE
Meteor 3.0

### ISSUE THREAD

**Issue by Sergeant61** [zodern/melte#32]
Hello, is there going to be any development for meteor.js 3.0? I would like to try the beta version in some of my projects.

**Comment by zodern** [comment]
I'm waiting for the next Meteor 3 release which will include https://github.com/meteor/meteor/pull/12930. I'm not expecting it to take much effort to support Meteor 3.

**Comment by jamauro** [comment]
Checking in on this one. Would be great to be able to use Svelte with Meteor 3. Thanks! 🙏🏼

**Comment by zodern** [comment]
I just released version 1.7.2, which is compatible with Meteor 1.8 - 3
